from __future__ import annotations

import re

# Corrige termos recorrentes sem acento no motor (ordem: frases longas primeiro).
_ACCENT_REPLACEMENTS: tuple[tuple[str, str], ...] = (
    ("nao da para", "não dá para"),
    ("nao se evita", "não se evita"),
    ("nao evitavel", "não evitável"),
    ("Parcialmente evitavel", "Parcialmente evitável"),
    ("Da para evitar", "Dá para evitar"),
    ("da para evitar", "dá para evitar"),
    ("nao ", "não "),
    ("Nao ", "Não "),
    ("voce ", "você "),
    ("Voce ", "Você "),
    (" tambem ", " também "),
    (" ja ", " já "),
    (" Ja ", " Já "),
    (" ate ", " até "),
    (" Ate ", " Até "),
    (" so ", " só "),
    (" So ", " Só "),
    (" acao ", " ação "),
    (" Acao ", " Ação "),
    (" decisao ", " decisão "),
    (" situacao ", " situação "),
    (" relacao ", " relação "),
    (" relacoes ", " relações "),
    (" separacao ", " separação "),
    (" definicao ", " definição "),
    (" reorganizacao ", " reorganização "),
    (" reorganizacao", " reorganização"),
    (" comunicacao ", " comunicação "),
    (" informacao ", " informação "),
    (" pressao ", " pressão "),
    (" funcao ", " função "),
    (" promocao ", " promoção "),
    (" posicao ", " posição "),
    (" condicao ", " condição "),
    (" emocional ", " emocional "),
    (" psicologico ", " psicológico "),
    (" astrologico ", " astrológico "),
    (" numerologico ", " numerológico "),
    (" numerologia ", " numerologia "),
    (" doenca ", " doença "),
    (" saude ", " saúde "),
    (" transito ", " trânsito "),
    (" Transito ", " Trânsito "),
    (" progressao ", " progressão "),
    (" Progressao ", " Progressão "),
    (" profeccao ", " profecção "),
    (" Profeccao ", " Profeccão "),
    (" conjuncao ", " conjunção "),
    (" Conjuncao ", " Conjunção "),
    (" oposicao ", " oposição "),
    (" Oposicao ", " Oposição "),
    (" trigono ", " trígono "),
    (" Trigono ", " Trígono "),
    (" quadratura ", " quadratura "),
    (" Mercurio", " Mercúrio"),
    (" Venus", " Vênus"),
    (" Jupiter", " Júpiter"),
    (" Plutao", " Plutão"),
    (" Saturno", " Saturno"),
    (" Capricornio", " Capricórnio"),
    (" Escorpiao", " Escorpião"),
    (" Aquario", " Aquário"),
    (" Sagitario", " Sagitário"),
    (" Gêmeos", " Gêmeos"),
    (" confianca ", " confiança "),
    (" consequencia ", " consequência "),
    (" virada ", " virada "),
    (" imprudencia", " imprudência"),
    (" irritacao ", " irritação "),
    (" disposicao ", " disposição "),
    (" imunologica ", " imunológica "),
    (" publica ", " pública "),
    (" forçada", " forçada"),
    (" forçada.", " forçada."),
    (" ciúme", " ciúme"),
    (" triangulo ", " triángulo "),
    (" humilhacao ", " humilhação "),
    (" confianca ou", " confiança ou"),
    (" proposito ", " propósito "),
    (" proposito", " propósito"),
    (" observacao ", " observação "),
    (" interpretacao ", " interpretação "),
    (" interpretativa ", " interpretativa "),
    (" tecnica ", " técnica "),
    (" tecnicas ", " técnicas "),
    (" tecnico ", " técnico "),
    (" analise ", " análise "),
    (" formacao", " formação"),
    (" formacao.", " formação."),
    (" proximo ", " próximo "),
    (" proximos ", " próximos "),
    (" proxima ", " próxima "),
    (" periodo ", " período "),
    (" periodos ", " períodos "),
    (" mes ", " mês "),
    (" meses ", " meses "),
    (" numerologica", " numerológica"),
    (" astrologica", " astrológica"),
)


def polish_portuguese(text: str) -> str:
    if not text:
        return text
    result = text
    for source, target in _ACCENT_REPLACEMENTS:
        result = result.replace(source, target)
    return re.sub(r" +", " ", result).strip()
